import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {useRouter} from 'next/router'
import {getAccessToken} from '../components/modules/42utils/token'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
	const router = useRouter();
	const token = router.query?.code;

	if (token) {
		getAccessToken(token as string);
		//router.push('/dashboard');
	}

	const genSiteLogo = () => {
		return (
			<div className={styles.logo}>
				<Image src="/logo.svg" width={100} height={100} layout="fixed" />
				<span className={styles.siteTitle}>Phoenix</span>
			</div>
		)
	}

	const genLogin = () => {
		return (
			<a href="https://api.intra.42.fr/oauth/authorize?client_id=7979f5a197e2d3ccf1f4b6e55abd6bb48e123040c4ad80428fc73d6c07250c94&redirect_uri=http%3A%2F%2Flocalhost%3A3000&response_type=code">
				<div className={styles.login}>
					<span>Se connecter</span>
				</div>
			</a>
		)
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Phoenix 42</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<main className={styles.main}>
				{genSiteLogo()}
				<span className={styles.help}>Pour continuer, connectez-vous via l'intra</span>
				{genLogin()}
			</main>
		</div>
	)
}

export default Home
