import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

	const genSiteLogo = () => {
		return (
			<div className={styles.logo}>
				<Image src="/logo.svg" width={100} height={100} layout="fixed" />
				<span className={styles.siteTitle}>Phoenix</span>
			</div>
		)
	}

	const genLogin = () => {
		return (
			<a href="/dashboard">
				<div className={styles.login}>
					<span>Se connecter</span>
				</div>
			</a>
		)
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Phoenix 42</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<main className={styles.main}>
				{genSiteLogo()}
				<span className={styles.help}>Pour continuer, connectez-vous via l'intra</span>
				{genLogin()}
			</main>
		</div>
	)
}

export default Home
